apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: readiness
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  {{- if and (eq .Values.target "aks") .Values.gateway.internal }}
  infrastructure:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  {{- end }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: readiness
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: readiness
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: readiness
          port: {{ .Values.service.port }}